name: Continuous Integration using GitHub Actions

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout Code
       uses: actions/checkout@v2
      
      -name: Setup .Net5
       uses: actions/setup-dotnet@v1.8.0

      -name: Restore Dependencies
       run: dotnet restore
      
      -name: Build Application
       run: dotnet build -c Release --no-restore

       
